const chalk = require('chalk');

console.log(chalk.red('---------------------------------------------'));
console.log(chalk.bold('bold'));
console.log(chalk.dim('dim'));
console.log(chalk.italic('italic'));
console.log(chalk.underline('underline'));
console.log(chalk.inverse('inverse'));
console.log(chalk.strikethrough('strikethrough'));
console.log(chalk.red('---------------------------------------------'));
console.log(chalk.red('red'));
console.log(chalk.green('green'));
console.log(chalk.yellow('yellow'));
console.log(chalk.blue('blue'));
console.log(chalk.magenta('magenta'));
console.log(chalk.cyan('cyan'));
console.log(chalk.white('white'));
console.log(chalk.gray('gray'));
console.log(chalk.bgBlack('bgBlack'));
console.log(chalk.red('---------------------------------------------'));
console.log(chalk.bgRed('bgRed'));
console.log(chalk.bgGreen('bgGreen'));
console.log(chalk.bgYellow('bgYellow'));
console.log(chalk.bgBlue('bgBlue'));
console.log(chalk.bgMagenta('bgMagenta'));
console.log(chalk.bgCyan('bgCyan'));
console.log(chalk.bgWhite('bgWhite'));
console.log(chalk.red('---------------------------------------------'));